# Generated by Django 4.0.6 on 2022-07-08 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='gg',
            new_name='gg11',
        ),
    ]
