# Generated by Django 4.0.6 on 2022-07-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0002_rename_gg_gg11'),
    ]

    operations = [
        migrations.AddField(
            model_name='gg11',
            name='NUm',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
