# Generated by Django 4.0.6 on 2022-07-12 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('e_mail', models.EmailField(max_length=150, null=True)),
                ('rank', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_article', models.CharField(max_length=2550)),
                ('text_post', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type_post', models.CharField(choices=[('news', 'Новости'), ('article', 'Статьи')], default='news', max_length=20)),
                ('sum_rank', models.IntegerField(default=0)),
                ('count_rank', models.IntegerField()),
                ('id_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.author')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_caregory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category')),
                ('id_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='id_category',
            field=models.ManyToManyField(through='news.PostCategory', to='news.category'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sum_rank', models.IntegerField(default=0)),
                ('count_rank', models.IntegerField(default=0)),
                ('id_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.post')),
                ('id_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.users')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='id_users',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='news.users'),
        ),
    ]
