# Generated by Django 4.0.6 on 2022-07-13 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='count_rank',
        ),
        migrations.RemoveField(
            model_name='post',
            name='count_rank',
        ),
    ]
