# Generated by Django 4.0.6 on 2022-07-14 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_author_id_users_alter_comments_id_users_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='id_caregory',
            new_name='id_category',
        ),
    ]
