# Generated by Django 4.0.6 on 2022-07-14 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_id_caregory_postcategory_id_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='id_category',
            new_name='category',
        ),
    ]
