# Generated by Django 4.0.6 on 2022-07-15 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0005_rename_id_category_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='id_users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='head_article',
            field=models.CharField(max_length=255),
        ),
    ]
